name: donor_darah
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  google_fonts: ^3.0.1
  google_maps: ^6.2.0
  image_picker: ^0.8.6
  google_maps_flutter: ^2.2.1
  pinput: ^2.2.16
  location: ^4.4.0
  cloud_firestore: ^4.0.4
  firebase_storage: ^11.0.4
  dropdown_button2: ^1.8.9
  equatable: ^2.0.5
  intl: ^0.17.0
  maps_launcher: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
