// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL5AbDAqJ3WGQtI1bqiJL_eYFOz49jXU0',
    appId: '1:113986626395:web:976d6c6a73b590c83ab07e',
    messagingSenderId: '113986626395',
    projectId: 'donor-darah-f3f8b',
    authDomain: 'donor-darah-f3f8b.firebaseapp.com',
    storageBucket: 'donor-darah-f3f8b.appspot.com',
    measurementId: 'G-8HE8XH3817',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ZlQeNLq7bgnHl2uVclYeuqOL1Q6blv8',
    appId: '1:113986626395:android:3980f9316094c1423ab07e',
    messagingSenderId: '113986626395',
    projectId: 'donor-darah-f3f8b',
    storageBucket: 'donor-darah-f3f8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7n-o39zoyBX8DJfgCTLGe4QsLdyYHHBw',
    appId: '1:113986626395:ios:bc474f862f8275fc3ab07e',
    messagingSenderId: '113986626395',
    projectId: 'donor-darah-f3f8b',
    storageBucket: 'donor-darah-f3f8b.appspot.com',
    iosClientId: '113986626395-pq2ag0dduosaie903ct4smf1s20n37t0.apps.googleusercontent.com',
    iosBundleId: 'com.dedek.donorDarah',
  );
}
